language: node_js
node_js: '12'
cache: yarn
env:
  global:
    - FORCE_COLOR=1
install:
  - yarn
jobs:
  include:
    - stage: test
      script:
        - yarn run prettier-check
        - yarn run eslint
        - yarn run build
        - eslint -f dist/formatter.js -c ./node_modules/eslint/conf/eslint-all.js -o dump.lsif 'src/**/*.ts' || true
        - node node_modules/lsif-util/bin/lsif-util validate dump.lsif
        # https://github.com/sourcegraph/lsif-test/issues/4
        # - go get github.com/sourcegraph/lsif-test/cmd/lsif-validate
        # - lsif-validate dump.lsif
    - stage: release
      script:
        - yarn run build
        - yarn run semantic-release
stages:
  - test
  - name: release
    if: branch = master AND type = push AND fork = false
branches:
  only:
    - master
    - /^renovate\//
